services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: ['postgres', '-c', 'wal_level=logical']
  #pgadmin:
  #  image: dpage/pgadmin4
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: 'test@test.com'
  #    PGADMIN_DEFAULT_PASSWORD: 'test'
  #  ports:
  #    - 16543:80
  #  volumes:
  #    - ./pgadmin-servers.json:/pgadmin4/servers.json
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    ports:
      - "6333:6333" # HTTP API & Web UI
      - "6334:6334" # gRPC API (High performance)
    volumes:
      - qdrant-db-volume:/qdrant/storage
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus-local
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - spring-ai-playground-network
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana-local
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - spring-ai-playground-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - spring-ai-playground-network
volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/temp/data/postgres
  qdrant-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/temp/data/qdrant
  grafana-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/temp/data/grafana
networks:
  spring-ai-playground-network:
    driver: bridge

