global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'ai-playground'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9191']