server:
  port: 9191
spring:
  application:
    name: ai-playground
  ai:
    ollama:
      init:
        pull-model-strategy: always
        timeout: 60s
        max-retries: 1
      chat:
        model: gpt-oss:latest
        options:
          temperature: 0.8
          max-tokens: 10000
      embedding:
        model: embeddinggemma:300m
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/schema-h2db.sql
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: ai-playground
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:~/temp/data/h2/chatmemory;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: test
    password: test123
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai.model.tool: DEBUG

playground:
  model:
    type: ${PLAYGROUND_MODEL_TYPE:ollama} #google-genai
  has-memory: false
  tavily-api-key: ${TAVILY_KEY:}
  tavily-result-limit: 5
  error-handling:
    type: assisted #assisted | manual