env:
  tavily-key: ${TAVILY_KEY:}
server:
  port: 9191
spring:
  application:
    name: ai-playground
  ai:
    ollama:
      init:
        pull-model-strategy: always
        timeout: 60s
        max-retries: 1
      chat:
        model: gemma3
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/schema-h2db.sql
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: ai-playground
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:~/temp/data/h2/chatmemory;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: test
    password: test123

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

playground:
  has-memory: false